import {
  mdiApi,
  mdiBellOutline,
  mdiBluetooth,
  mdiBug,
  mdiCalendarClock,
  mdiCameraOutline,
  mdiCardTextOutline,
  mdiChartLine,
  mdiCheckboxMarkedCircleOutline,
  mdiChip,
  mdiClockOutline,
  mdiCloudUploadOutline,
  mdiCodeArray,
  mdiCodeBraces,
  mdiCodeJson,
  mdiCog,
  mdiConnection,
  mdiContentSaveCogOutline,
  mdiCpu32Bit,
  mdiCrosshairsGps,
  mdiDialpad,
  mdiEthernet,
  mdiExportVariant,
  mdiFan,
  mdiFingerprint,
  mdiFormatFont,
  mdiFormDropdown,
  mdiFormTextbox,
  mdiGauge,
  mdiGestureTapButton,
  mdiImageMultipleOutline,
  mdiImageOutline,
  mdiImageSyncOutline,
  mdiLan,
  mdiLedOn,
  mdiLightbulbOutline,
  mdiLockOutline,
  mdiMemory,
  mdiMicrophone,
  mdiMicrophoneMessage,
  mdiMonitor,
  mdiMotionSensor,
  mdiNfcVariant,
  mdiNumeric,
  mdiPackageVariantClosed,
  mdiPalette,
  mdiPoundBoxOutline,
  mdiPowerPlug,
  mdiPowerSleep,
  mdiPuzzleOutline,
  mdiQrcode,
  mdiRadioTower,
  mdiRemote,
  mdiRestartAlert,
  mdiScriptTextOutline,
  mdiSerialPort,
  mdiShapeOutline,
  mdiShieldHomeOutline,
  mdiSpeaker,
  mdiSprinklerVariant,
  mdiSwapHorizontal,
  mdiTextBoxOutline,
  mdiThermostat,
  mdiToggleSwitchOutline,
  mdiUsb,
  mdiValve,
  mdiVariable,
  mdiVolumeHigh,
  mdiVpn,
  mdiWeatherSunny,
  mdiWeb,
  mdiWifi,
  mdiWifiCog,
  mdiWifiLock,
  mdiWindowShutter,
  mdiZigbee,
  mdiZWave,
} from "@mdi/js";
import { RP2_ALIAS_KEY, RP2_CANONICAL_KEY } from "../../util/component-presence.js";

/**
 * Per-domain leading glyph for navigator rows, so a long Core or
 * Components list can be scanned by shape. Keyed on the YAML domain
 * (``item.key``); the value is the mdi svg path, rendered inline.
 * Platform components inherit their domain's glyph (``light``, ``sensor``,
 * …); only top-level keys need an entry, and the niche long tail falls
 * through to {@link FALLBACK}.
 */
const DOMAIN_ICON: Record<string, string> = {
  // Core infrastructure
  esphome: mdiChip,
  wifi: mdiWifi,
  ethernet: mdiEthernet,
  mdns: mdiRadioTower,
  network: mdiLan,
  api: mdiApi,
  ota: mdiCloudUploadOutline,
  dashboard_import: mdiCloudUploadOutline,
  logger: mdiCardTextOutline,
  syslog: mdiCardTextOutline,
  web_server: mdiWeb,
  http_request: mdiWeb,
  captive_portal: mdiWifiLock,
  improv_serial: mdiWifiCog,
  esp32_improv: mdiWifiCog,
  mqtt: mdiSwapHorizontal,
  wireguard: mdiVpn,
  socket: mdiConnection,
  udp: mdiConnection,
  async_tcp: mdiConnection,
  espnow: mdiConnection,
  serial_proxy: mdiConnection,
  sim800l: mdiConnection,
  prometheus: mdiChartLine,
  statsd: mdiChartLine,
  runtime_stats: mdiChartLine,
  time: mdiClockOutline,
  sntp: mdiClockOutline,
  interval: mdiClockOutline,
  script: mdiScriptTextOutline,
  uart: mdiSerialPort,
  i2c: mdiConnection,
  spi: mdiConnection,
  modbus: mdiConnection,
  modbus_controller: mdiConnection,
  modbus_server: mdiConnection,

  // Board platforms
  esp32: mdiCpu32Bit,
  esp8266: mdiCpu32Bit,
  [RP2_CANONICAL_KEY]: mdiCpu32Bit,
  // the deprecated rp2040 spelling of the rp2 platform (esphome#17145)
  [RP2_ALIAS_KEY]: mdiCpu32Bit,
  bk72xx: mdiCpu32Bit,
  rtl87xx: mdiCpu32Bit,
  ln882x: mdiCpu32Bit,
  libretiny: mdiCpu32Bit,
  nrf52: mdiCpu32Bit,
  host: mdiChip,
  esp32_hosted: mdiWifi,

  // Bluetooth family
  esp32_ble: mdiBluetooth,
  esp32_ble_tracker: mdiBluetooth,
  ble: mdiBluetooth,
  bluetooth_proxy: mdiBluetooth,
  ble_client: mdiBluetooth,
  ble_nus: mdiBluetooth,
  esp32_ble_beacon: mdiBluetooth,
  esp32_ble_server: mdiBluetooth,
  zephyr_ble_server: mdiBluetooth,
  rp2040_ble: mdiBluetooth,
  exposure_notifications: mdiBluetooth,
  airthings_ble: mdiBluetooth,
  bedjet: mdiBluetooth,
  mopeka_ble: mdiBluetooth,
  radon_eye_ble: mdiBluetooth,
  ruuvi_ble: mdiBluetooth,
  xiaomi_ble: mdiBluetooth,
  xiaomi_rtcgq02lm: mdiBluetooth,

  // Mesh radios
  zwave_proxy: mdiZWave,
  zigbee: mdiZigbee,
  openthread: mdiZigbee,

  // USB
  usb_host: mdiUsb,
  usb_uart: mdiUsb,
  usb_cdc_acm: mdiUsb,
  tinyusb: mdiUsb,

  // Power / memory / lifecycle
  psram: mdiMemory,
  preferences: mdiContentSaveCogOutline,
  power_supply: mdiPowerPlug,
  esp_ldo: mdiPowerPlug,
  sy6970: mdiPowerPlug,
  deep_sleep: mdiPowerSleep,
  status_led: mdiLedOn,
  safe_mode: mdiRestartAlert,
  factory_reset: mdiRestartAlert,
  debug: mdiBug,

  // Config / data utilities
  globals: mdiVariable,
  substitutions: mdiCodeBraces,
  packages: mdiPackageVariantClosed,
  external_components: mdiPuzzleOutline,
  mapping: mdiCog,
  json: mdiCodeJson,
  bytebuffer: mdiCodeArray,
  split_buffer: mdiCodeArray,
  sha256: mdiPoundBoxOutline,
  hmac_md5: mdiPoundBoxOutline,
  hmac_sha256: mdiPoundBoxOutline,

  // Remote / sub-GHz / IR radios
  remote_receiver: mdiRemote,
  remote_transmitter: mdiRemote,
  cc1101: mdiRemote,
  sx126x: mdiRemote,
  sx127x: mdiRemote,
  lightwaverf: mdiRemote,
  rf_bridge: mdiRemote,

  // NFC / RFID readers
  pn532: mdiNfcVariant,
  pn532_i2c: mdiNfcVariant,
  pn532_spi: mdiNfcVariant,
  pn7150_i2c: mdiNfcVariant,
  pn7160_i2c: mdiNfcVariant,
  pn7160_spi: mdiNfcVariant,
  rc522_i2c: mdiNfcVariant,
  rc522_spi: mdiNfcVariant,
  rdm6300: mdiNfcVariant,

  // Presence / radar
  ld2410: mdiMotionSensor,
  ld2412: mdiMotionSensor,
  ld2420: mdiMotionSensor,
  ld2450: mdiMotionSensor,
  rd03d: mdiMotionSensor,
  at581x: mdiMotionSensor,
  dfrobot_sen0395: mdiMotionSensor,
  hlk_fm22x: mdiMotionSensor,
  seeed_mr24hpc1: mdiMotionSensor,
  seeed_mr60bha2: mdiMotionSensor,
  seeed_mr60fda2: mdiMotionSensor,

  // Touch / keypad / biometric
  esp32_touch: mdiGestureTapButton,
  cap1188: mdiGestureTapButton,
  mpr121: mdiGestureTapButton,
  ttp229_bsf: mdiGestureTapButton,
  ttp229_lsf: mdiGestureTapButton,
  matrix_keypad: mdiDialpad,
  wiegand: mdiDialpad,
  key_collector: mdiDialpad,
  fingerprint_grow: mdiFingerprint,

  // Audio
  i2s_audio: mdiVolumeHigh,
  audio: mdiVolumeHigh,
  audio_file: mdiVolumeHigh,
  microphone: mdiMicrophone,
  micro_wake_word: mdiMicrophone,
  voice_assistant: mdiMicrophoneMessage,
  speaker: mdiSpeaker,
  dfplayer: mdiSpeaker,
  rtttl: mdiSpeaker,

  // LED drivers / strip protocols
  adalight: mdiLightbulbOutline,
  wled: mdiLightbulbOutline,
  e131: mdiLightbulbOutline,
  my9231: mdiLightbulbOutline,
  sm16716: mdiLightbulbOutline,
  sm2135: mdiLightbulbOutline,
  sm2235: mdiLightbulbOutline,
  sm2335: mdiLightbulbOutline,
  bp1658cj: mdiLightbulbOutline,
  bp5758d: mdiLightbulbOutline,
  tlc59208f: mdiLightbulbOutline,
  tlc5947: mdiLightbulbOutline,
  tlc5971: mdiLightbulbOutline,
  tm1651: mdiLightbulbOutline,

  // ADC / DAC
  adc128s102: mdiGauge,
  ads1115: mdiGauge,
  ads1118: mdiGauge,
  mcp3008: mdiGauge,
  mcp3204: mdiGauge,
  as5600: mdiGauge,
  dac7678: mdiExportVariant,
  gp8403: mdiExportVariant,
  mcp4728: mdiExportVariant,
  mcp4461: mdiExportVariant,
  pca9685: mdiExportVariant,
  servo: mdiExportVariant,
  grove_tb6612fng: mdiExportVariant,

  // IO / bus expanders, muxes, UART bridges
  mcp23008: mdiConnection,
  mcp23016: mdiConnection,
  mcp23017: mdiConnection,
  mcp23s08: mdiConnection,
  mcp23s17: mdiConnection,
  pca6416a: mdiConnection,
  pca9554: mdiConnection,
  pcf8574: mdiConnection,
  pi4ioe5v6408: mdiConnection,
  xl9535: mdiConnection,
  max6956: mdiConnection,
  sn74hc165: mdiConnection,
  sn74hc595: mdiConnection,
  cd74hc4067: mdiConnection,
  tca9548a: mdiConnection,
  tca9555: mdiConnection,
  ch422g: mdiConnection,
  ch423: mdiConnection,
  sx1509: mdiConnection,
  m5stack_8angle: mdiConnection,
  i2c_device: mdiConnection,
  spi_device: mdiConnection,
  vbus: mdiConnection,
  tuya: mdiConnection,
  wk2132_i2c: mdiSerialPort,
  wk2132_spi: mdiSerialPort,
  wk2168_i2c: mdiSerialPort,
  wk2168_spi: mdiSerialPort,
  wk2204_i2c: mdiSerialPort,
  wk2204_spi: mdiSerialPort,
  wk2212_i2c: mdiSerialPort,
  wk2212_spi: mdiSerialPort,

  // Chip / environment / meter sensors
  apds9960: mdiGauge,
  as3935_i2c: mdiGauge,
  as3935_spi: mdiGauge,
  bme680_bsec: mdiGauge,
  bme68x_bsec2_i2c: mdiGauge,
  gdk101: mdiGauge,
  msa3xx: mdiGauge,
  ezo_pmp: mdiGauge,
  daly_bms: mdiGauge,
  pylontech: mdiGauge,
  pipsolar: mdiGauge,
  sun_gtil2: mdiGauge,
  sml: mdiGauge,
  dsmr: mdiGauge,
  teleinfo: mdiGauge,
  dlms_meter: mdiGauge,
  emontx: mdiGauge,
  emc2101: mdiFan,
  gps: mdiCrosshairsGps,
  sun: mdiWeatherSunny,

  // Climate / heating / irrigation
  opentherm: mdiThermostat,
  uponor_smatrix: mdiThermostat,
  micronova: mdiThermostat,
  sprinkler: mdiSprinklerVariant,

  // Component platforms
  sensor: mdiGauge,
  binary_sensor: mdiCheckboxMarkedCircleOutline,
  text_sensor: mdiTextBoxOutline,
  switch: mdiToggleSwitchOutline,
  light: mdiLightbulbOutline,
  output: mdiExportVariant,
  number: mdiNumeric,
  select: mdiFormDropdown,
  button: mdiGestureTapButton,
  fan: mdiFan,
  cover: mdiWindowShutter,
  climate: mdiThermostat,
  text: mdiFormTextbox,
  lock: mdiLockOutline,
  valve: mdiValve,
  media_player: mdiSpeaker,
  display: mdiMonitor,
  lvgl: mdiMonitor,
  graphical_display_menu: mdiMonitor,
  lcd_menu: mdiMonitor,
  datetime: mdiCalendarClock,
  camera: mdiCameraOutline,
  esp32_camera: mdiCameraOutline,
  esp32_camera_web_server: mdiCameraOutline,
  camera_encoder: mdiCameraOutline,
  event: mdiBellOutline,
  alarm_control_panel: mdiShieldHomeOutline,

  // Graphics
  graph: mdiChartLine,
  color: mdiPalette,
  qr_code: mdiQrcode,
  font: mdiFormatFont,
  image: mdiImageOutline,
  online_image: mdiImageSyncOutline,
  animation: mdiImageMultipleOutline,
};

/** Neutral glyph for any domain not in {@link DOMAIN_ICON}. */
const FALLBACK = mdiShapeOutline;

/** mdi svg path for a row's domain; neutral shape if unmapped.
 *  Automation rows pass their ``parentKey`` (the targeted component domain),
 *  so the glyph matches that component (binary_sensor, switch, …). */
export function iconPathForDomain(domain: string): string {
  return DOMAIN_ICON[domain] ?? FALLBACK;
}
