name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint"
      - ".github/workflows/yamllint.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run yamllint
        run: yamllint .
