name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint"
      - ".github/workflows/yamllint.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run yamllint
        run: yamllint .
